clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      skip_verify: true

steps:
  update_site:
    image: alpine/git
    volumes:
      - /home/ngurley/nicholasegurley.github.io:/home/ngurley/nicholasegurley.github.io
    commands:
      - git config --global http.sslVerify false
      - git config --global --add safe.directory /home/ngurley/nicholasegurley.github.io
      - cd /home/ngurley/nicholasegurley.github.io
      - git fetch origin
      - git reset --hard origin/main
      - chown -R ngurley:ngurley /home/ngurley/nicholasegurley.github.io
    when:
      event: push
      branch: main

  restart_jekyll:
    image: alpine
    privileged: true
    volumes:
      - /home/ngurley/nicholasegurley.github.io:/home/ngurley/nicholasegurley.github.io
    commands:
      - apk add --no-cache bash
      - bash -lc "systemctl restart jekyll-dev"
    when:
      event: push
      branch: main

