workflow:
  when:
    event: [ push ]
    branch: [ main ]

steps:
  update_site:
    image: alpine/git
    commands:
      - cd /home/ngurley/nicholasegurley.github.io
      - git fetch origin
      - git reset --hard origin/main
      - chown -R ngurley:ngurley /home/ngurley/nicholasegurley.github.io

  restart_jekyll:
    image: alpine
    privileged: true
    commands:
      - apk add --no-cache bash
      - bash -lc "systemctl restart jekyll-dev"

