clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip_verify: true
      depth: 1

steps:
  update_site:
    image: alpine/git
    volumes:
      - /home/ngurley/nicholasegurley.github.io:/site
      - /home/ngurley/.ssh:/root/.ssh
    environment:
      HOME: /root
      GITEA_HOST: "gitea.autostack.lan"
      GITEA_PORT: "2222"
    commands:
      - git config --global http.sslVerify false
      - git config --global safe.directory /site

      # Ensure known_hosts contains the Gitea SSH fingerprint
      - ssh-keyscan -p $GITEA_PORT $GITEA_HOST >> /root/.ssh/known_hosts

      - cd /site

      # Force the repo to use SSH origin inside the container
      - git remote set-url origin ssh://git@$GITEA_HOST:$GITEA_PORT/ngurley/nicholasegurley.github.io.git

      # Now fetch from Gitea via SSH
      - git fetch origin
      # - git reset --hard origin/main
      - git pull

      #- chown -R 1001:1001 /site
    when:
      event: push
      branch: demo
