pipeline:
  update_site:
    image: alpine/git
    commands:
      - cd /home/ngurley/nicholasegurley.github.io
      - git fetch origin
      - git reset --hard origin/main
      - chown -R ngurley:ngurley /home/ngurley/nicholasegurley.github.io

  restart_jekyll:
    image: alpine
    commands:
      - echo "Restarting Jekyll service..."
      - apk add --no-cache bash
      - bash -lc "systemctl restart jekyll-dev"
    privileged: true
    when:
      branch: main
